### ISSUE TITLE
Quilt installer failing

### ISSUE THREAD

**Issue by walksanatora** [QuiltMC/quiltmc.org#126]
I am trying to install quiltmc using the Universal .jar file with the following arguments
```
java -jar quilt-installer-0.5.0.jar install client 1.19.2 --install-dir=/home/walksanator/.local/share/PrismLauncher/instances/1.19.2/.minecraft/
```
when I try and do this it crashes with
```
Failed to install client
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://meta.quiltmc.org/v3/versions/loader
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.UncheckedIOException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://meta.quiltmc.org/v3/versions/loader
	at org.quiltmc.installer.QuiltMeta.lambda$create$1(QuiltMeta.java:129)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://meta.quiltmc.org/v3/versions/loader
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.quiltmc.installer.QuiltMeta.lambda$create$1(QuiltMeta.java:123)
	... 7 more
```
I can curl and go to the url directly, but automated installs fail

**Comment by Akarys42** [comment]
Hello, thank you for the report. Are you currently connected via Tor?

**Comment by walksanatora** [comment]
I did try both with and without proxy over tor, same error both times

**Comment by walksanatora** [comment]
because either I get ^ with `proxychains` over TOR or I get
```
Installing Minecraft client at: /home/walksanator/.local/share/PrismLauncher/instances/1.19.2/.minecraft
Installing Minecraft client of version 1.19.2 with loader version 0.19.0-beta.12
Failed to install client
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.net.SocketException: Connection reset
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.UncheckedIOException: java.net.SocketException: Connection reset
	at org.quiltmc.installer.VersionManifest.lambda$create$0(VersionManifest.java:60)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.quiltmc.installer.VersionManifest.lambda$create$0(VersionManifest.java:54)
	... 7 more
	```

**Comment by walksanatora** [comment]
(I am trying manually because prism is having problems also)

**Comment by walksanatora** [comment]
just noticed, prism had proxy enabled, turning off and re-trying

**Comment by walksanatora** [comment]
yep it was the proxy over tor
